#!/bin/sh
## Bootstrap shell script to initialize the build
## This script produces the configure script
##
## Copyright (C) 2009,2010,201,2012
## Carsten Lemmen <carsten.lemmen@hzg.de>
## GKSS-Forschungszentrum Geesthacht GmbH
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2, or (at your option)
## any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
## 02110-1301, USA.

AUTORECONF=`which autoreconf`

if test -x $AUTORECONF  ; then 
  aclocal -I ../../config && autoheader \
  && automake --foreign --add-missing --copy\
  && autoconf
else
  autoreconf --install --verbose
fi

# temporary bug fix for missing LT_INIT macro
if test -f configure ; then
  sed '/LT_INIT/d' configure > configure.tmp
  mv configure.tmp configure
fi

# temporary bug fix for missing _LT_DECL macro
if test -f configure ; then
  sed '/_LT_DECL/d;/build shared libraries/d' configure > configure.tmp
  mv configure.tmp configure
fi

test -x ./configure || chmod +x ./configure
