function [directories]=cl_init
%CL_INIT initialised the directories used by glues

%  this file is automatically generated from cl_init.m.in
%

d.share='/usr/local/share/glues';
d.bin='/usr/local/bin';

d.extern=fullfile(d.share,'extern');

if (nargout>0)
  directories=d;
end
    
return
end