function do_pakistan

plots=[1,3];

%% Load country boundaries
load('../../data/naturalearth/10m_admin_0_countries.mat');
for i=1:length(shape)
    if strmatch(shape(i).SOVEREIGNT,'Pakistan') ipak=i; break; end
end
plat=shape(ipak).Y;
plon=shape(ipak).X;
latlim=[min(plat) max(plat)] + 0.5*[-1 1];
lonlim=[min(plon) max(plon)] + 0.5*[-1 1];

%% Load site data
% This file is generated by plot_randall_periods.m and has
% information p_index and p_time for certain periods in the whole dataset
load 'randall_ivc_data_periods.mat';
  
% Load the whole data set
data=load('../../data/randall_ivc_data');
period=data.period';
im=[
  strmatch('Accharwala',period);
  strmatch('Ahar-Banas',period);
  strmatch('Amri',period);
  strmatch('Anarta',period);
  strmatch('Andrhra',period);
  strmatch('Anjira',period);
  strmatch('BMAC',period);
  strmatch('Bara',period);
  strmatch('Bhurj',period);
  strmatch('Bihar',period);
  strmatch('Black',period);
  strmatch('Buddhist',period);
  strmatch('Burj',period);
  strmatch('Burnished',period);
  strmatch('Cem',period);
  strmatch('Chalcolithic',period);
  strmatch('Complex B',period);
  strmatch('Damb Sadaat',period);
  strmatch('Dasht',period);
  strmatch('Early',period);
  strmatch('GAZ',period);
  strmatch('Ganeshwar',period);
  strmatch('Grindingstone',period);
  strmatch('Gujarat',period);
  strmatch('Gupta',period);
  strmatch('Hakra Wares',period);
  strmatch('Harappan',period);
  strmatch('Haryana',period);
  strmatch('Historic',period);
  strmatch('Iron Age',period);
  strmatch('Islamic',period);
  strmatch('Jhangar',period);
  strmatch('Jhukar',period);
  strmatch('Jodhpura',period);
  strmatch('Kaisaria',period);
  strmatch('Kechi',period);
  strmatch('Kerman',period);
  strmatch('Kili',period);
  strmatch('Kingrali',period);
  strmatch('Kirana',period);
  strmatch('Kot Diji',period);
  strmatch('Kulli',period);
  strmatch('Kushan',period);
  strmatch('Late',period);
  strmatch('Londo',period);
  strmatch('Lustrous Red Ware',period);
  strmatch('Madhya Preadesh',period);
  strmatch('Maharashtra',period);
  strmatch('Malwa',period);
  strmatch('Mature and Late Harappan',period);
  strmatch('Medieval',period);
  strmatch('Mehrgarh',period);
  strmatch('Microliths',period);
  strmatch('NBP',period);
  strmatch('Nal',period);
  strmatch('Northern Neolithic',period);
  strmatch('OCP',period);
  strmatch('Orissa',period);
  strmatch('PGW',period);
  strmatch('Palaeo / Mesolithic',period);
  strmatch('Partho',period);
  strmatch('Pirak',period);
  strmatch('Post',period);
  strmatch('Prabhas',period);
  strmatch('Pre-',period);
  strmatch('Quetta',period);
  strmatch('Rajasthan',period);
  strmatch('Rang Mahal',period);
  strmatch('Rangpur',period);
  strmatch('Ravi',period);
  strmatch('Red Polished Ware',period);
  strmatch('SKT',period);
  strmatch('Shahi Tump',period);
  strmatch('Shinkai',period);
  strmatch('Sistan',period);
  strmatch('Sorath',period);
  strmatch('Sothi-Siswal',period);
  strmatch('Sulaiman',period);
  strmatch('Sunga-Kushan',period);
  strmatch('Swat',period);
  strmatch('TERIA',period);
  strmatch('Thari',period);
  strmatch('Togau',period);
  strmatch('Uttarpradesh',period);
  strmatch('Waziri',period);
  strmatch('Zangian',period);
];
nall=length(period);
narch=length(im);
period=period(im);
rlat=data.latitude(im);
rlon=data.longitude(im);

randall=cl_randall_periods;
info={'Kili','Burj','Bhurj','Togau','SKT','Hakra','Kechi','Anarta'};
fprintf('Randall''s data set contains %d data, of these %d archaeological.\n',nall,narch);
for i=1:length(info)
  im=strmatch(info{i},data.period);
  fprintf('Period: %s \n',char(unique(data.period(im))));
  fprintf('  there are %d artifacts at %d sites \n',...
    length(im),length(unique(data.sitename(im))));
  usitenames=unique(data.sitename(im));
  fprintf('  %s \n',usitenames{:});
  fprintf('  spanning %.1f-%.1f E and %.1f-%.1f N\n\n',...
    min(data.longitude(im)),max(data.longitude(im)),...
    min(data.latitude(im)),max(data.latitude(im)));

end

% From Harappan-sites.kml
% Early Harappa 5000-2600 BC: Ravi + Hakra + Amri-Nal + Sothi-Siswal 
% + Kot Diji 
% Harappan: 2600-1900 BC: Harappa + Cities + Jhukar + Jhangar 
% + Late Sorath 
% Post-Urban: Post-Urban + Late harappan + Cemetery H




timelim=[[-9000 p_times]' , [p_times -1900]'];
timelim=cell2mat(timelim);
tlim=[min(min(timelim)) max(max(timelim))];


%% Load simulation data
file='../../eurolbk_events.nc';
ncid=netcdf.open(file,'NOWRITE');
varid=netcdf.inqVarID(ncid,'region'); region=netcdf.getVar(ncid,varid);
varid=netcdf.inqVarID(ncid,'longitude'); longitude=netcdf.getVar(ncid,varid);
varid=netcdf.inqVarID(ncid,'latitude'); latitude=netcdf.getVar(ncid,varid);
varid=netcdf.inqVarID(ncid,'time'); time=netcdf.getVar(ncid,varid);
varid=netcdf.inqVarID(ncid,'area'); area=netcdf.getVar(ncid,varid);
varid=netcdf.inqVarID(ncid,'population_density'); pdensity=netcdf.getVar(ncid,varid);
varid=netcdf.inqVarID(ncid,'population_size'); psize=netcdf.getVar(ncid,varid);
varid=netcdf.inqVarID(ncid,'technology'); technology=netcdf.getVar(ncid,varid);
varid=netcdf.inqVarID(ncid,'farming'); farming=netcdf.getVar(ncid,varid);
varid=netcdf.inqVarID(ncid,'natural_fertility'); natfert=netcdf.getVar(ncid,varid);
varid=netcdf.inqVarID(ncid,'temperature_limitation'); templim=netcdf.getVar(ncid,varid);
netcdf.close(ncid);


%% Do plots
global naturalearth

if any(plots==3)
  figure(3); clf reset;
  m_proj('equidistant','lat',latlim,'lon',lonlim);
  pe=clp_naturalearth('lat',latlim,'lon',lonlim);
  %mb=m_patch(plon,plat,'y','FaceAlpha',0.3,'EdgeColor','k','EdgeAlpha',0.5);
  mb=m_patch(plon,plat,'y','FaceAlpha',0.,'EdgeColor','r','EdgeAlpha',1,'LineStyle','-','LineWidth',2);
  m_grid; hold on;
  im=find(rlon>=lonlim(1) & ...
      rlon<=lonlim(2) & ...
      rlat>=latlim(1) & ...
      rlat<=latlim(2));
  parch=m_plot(rlon(im),rlat(im),'k.','MarkerSize',6,'Color',repmat(0.5,1,3));
  fprintf('Found %d sites in geographic area',length(im));
  irandall=[strmatch('Neolithic',randall.period) ; strmatch('Pre-Harappan',randall.period)];
  ifarm=[randall.index{irandall(1)}; randall.index{irandall(2)}];
  rlat=data.latitude(ifarm);
  rlon=data.longitude(ifarm);

  im=find(rlon>=lonlim(1) & ...
      rlon<=lonlim(2) & ...
      rlat>=latlim(1) & ...
      rlat<=latlim(2));
  pneolithic=m_plot(rlon(im),rlat(im),'r.','MarkerSize',6,'Color',repmat(0.2,1,3));
  fprintf('Found %d agricultural sites in geographic area',length(im));
  
  cities={'Togau','Kechi Beg','Amri','Harappa',...
      'Mohenjo-Daro','Harappa','Mehrgarh'};
  for i=1:length(cities)
    icity=strmatch(cities{i},data.sitename);
    if isempty(icity) continue; end
    pc(i)=m_plot(data.longitude(icity(1)),data.latitude(icity(1)),'ko',...
      'MarkerFaceColor','r','MarkerSize',10,'tag',[cities{i} '/' data.period{icity(1)}]);
    pct(i)=m_text(data.longitude(icity(1))+0.2,data.latitude(icity(1)),...
      cities{i},'FontSize',12,'Color',[0.3 0 0]);
  end
  cl_print('name','../plots/map/pakistan_randall_sites_neolithic','ext','png');
  
end

[ifound,nfound,lonlim,latlim]=find_region_numbers('lat',latlim,'lon',lonlim);    

if any(plots==4)
  figure(4); clf reset;
  rarea=repmat(area,1,length(time));
  natfertmax=repmat(max(natfert,[],2),1,length(time));
  itime=find(time>=-7000 & time<=-2666);
  climdist=natfert(ifound,itime)./natfertmax(ifound,itime);
  
  plot(mean(climdist),time(itime),'k-','LineWidth',4);
  set(gca,'box','off','color','none');
  cl_print('name','../plots/harappa_resource_depletion','ext','pdf');
  
end

if any(plots==1)

  threshold=0.5;
  ntime=1;
  timing=(farming>=threshold)*1.0;
  izero=find(timing==0);
  timing(izero)=NaN;
  timing=timing.*repmat(time',size(farming,1),1);
  timing(isnan(timing))=inf;
  timing=min(timing,[],2);
  timing(isinf(timing))=NaN;
  
  [hp,loli,lali,lon,lat]=clp_regionpath('lat',latlim,'lon',lonlim,'draw','patch','col','k');  
  ival=find(hp>0);
  alpha(hp(ival),0.);

  set(parch,'visible','off');
  set(pneolithic,'visible','off');
  set(pc,'visible','off');
  set(pct,'visible','off');
 % [d,b]=clp_nc_variable('var','farming','thresh',0.5','showstat',0,...
 % 'noprint',1,'latlim',latlim,'lonlim',lonlim,...
 % 'timelim',tlim,'file','../../eurolbk_events.nc','showtime',0);
  
  cmap=jet(5);
  colorbar;
  colormap(cmap);
  
  plim=[1 4];
  
  for i=max(plim)+1:-1:min(plim)+1
     iperiod=find(timing(ifound)<=timelim(i,2) & timing(ifound)>=timelim(i,1) & hp'>0);
     if ~isempty(iperiod)   
       set(hp(iperiod),'FaceColor',cmap(i,:),'FaceAlpha',1);
     end
     if (i>1 & i<7)
       p(i)=m_plot(data.longitude(p_index{i-1}),data.latitude(p_index{i-1}),...
         'ko','MarkerFaceColor',cmap(i,:),'MarkerSize',19);
       uistack(p(i),'top');
     end
  end
  ax=gca;
  cbar=cl_colorbar('val',cell2mat(p_times(plim(1):plim(2)+1)),'cmap',cmap(plim(1)+1:plim(2)+1,:));
  axes(ax);
  
  ct=get(cbar,'title');
  ytl=get(cbar,'YTickLabel');
  set(cbar,'YTickLabel',num2str(abs(str2num(ytl))));
  
  set(ct,'string','cal BC');
  title(' Indus valley neolithization and site chronology');
  cl_print('name','../plots/variable/farming/pakistan_farming_threshold','ext','png');
  
end

if any(plots==2)
  % Find pakistan regions
  %[d,b]=clp_nc_variable('var','region','showstat',0,...
  %'noprint',1,'latlim',latlim+5*[-1 1],'lonlim',lonlim+5*[-1 1],'showvalue',1,...
  %'file','../../eurolbk_events.nc');
  %pakreg=[368 375 360 346 337 328 317 308];
  allindex=[];
  for i=1:3 allindex=vertcat(allindex,p_index{i}); end
  pakreg=cl_regionfind(d.lon,d.lat,data.longitude(allindex),data.latitude(allindex),500);
  
 

  timepoints=mean(timelim,2);
  n=10;
  for i=1:length(p_index) n(i+1)=length(p_index{i}); end
  
  figure(1); clf reset;
  hold on;
  %plot(timepoints,n,'b.','Marker','o');
  set(gca,'xlim',tlim,'ylim',[0 4E5]);
  
  % Surovell (2009) taphonomic correction based
  % on volcanic ash deposits
  nt=flipud(5.73E6*(2176.4+1950-timepoints).^-1.39);
  %plot(timepoints,nt.*n','r.','Marker','o');
  
  yi=interp1(timepoints,nt.*n',time,'spline');
  %plot(time,yi,'r-','Linewidth',4);

  s=sum(psize(d.region(pakreg),:));
  %plot(time,s,'r-');
  
  ax=plotyy(time,yi,time,s);
  set(ax,'Xlim',[-8000 -2000]);
  set(ax(1),'YLim',[0 5E4]);
  legend('Number of artifacts','location','NorthWest');
  axes(ax(2));
  legend('Population of Neolithic Indus valley','location','NorthEast');
 
end


return;
end

function index=cl_regionfind(lon1,lat1,lon2,lat2,rmax)

  if ~exist('rmax','var') rmax=500; end

  if size(lon1,1)==1 lon1=lon1'; end
  if size(lon2,1)==1 lon2=lon2'; end
  if size(lat1,1)==1 lat1=lat1'; end
  if size(lat2,1)==1 lat2=lat2'; end
  
  n1=length(lon1);
  n2=length(lon2);
  
  index=[];
  for i=1:n1
     lo1=repmat(lon1(i),n2,1);
     la1=repmat(lat1(i),n2,1);
     
     lo2=reshape([lo1,lon2]',2*n2,1);
     la2=reshape([la1,lat2]',2*n2,1);
     
     dist=m_lldist(lo2,la2);
     dist=dist(1:2:2*n2-1);
     [mindist,imindist]=min(dist);
     if mindist<=rmax index=vertcat(index,i); end
  end


return;
end














function none
%% Finds correlation between CRU and Indus varves
crufile='data/tyn_cru2.0_bycountry_pakistan.txt';
varvefile='data/indus_varves.mat';

cru=load(crufile,'-ascii');
varve=load(varvefile);
icru=find (cru(:,1)<1980 & cru(:,1)>1901);
ivarve=find (varve.year<1980 & varve.year>1901);

figure(1); clf reset;
plot(varve.year(ivarve),cl_normalize(varve.thick(ivarve)),'r-','Linewidth',3);

ropt=0
for i=2:18
  for j=30:80
    c=movavg(cru(icru,1),cru(icru,i),j);
    for k=-10:10
      v=varve.thick(ivarve+k);
      r=corrcoef(v,c);
      if abs(r(1,2))>abs(ropt)
        ropt=r(1,2); kopt=k; jopt=j; iopt=i;
        fprintf('%f %d %d %d\n',ropt,k,i,j);
      end
    end
  end
end
 
c=cl_normalize(movavg(cru(icru,1),cru(icru,iopt),jopt));
v=cl_normalize(varve.thick(ivarve+kopt));

hold off;
plot(varve.year(ivarve),v,'r-','Linewidth',3);
hold on;
p(i)=plot(cru(icru,1),c,'b-');
  
return

lonlim=[60,80];
latlim=[22 38];
clp_topography('latlim',latlim,'lonlim',lonlim);
m_proj('equidistant','lat',latlim,'lon',lonlim);

%%
file='data/plasim_11k.nc';
ncid=netcdf.open(file,'NOWRITE');
varid=netcdf.inqVarID(ncid,'lat'); lat=netcdf.getVar(ncid,varid);
varid=netcdf.inqVarID(ncid,'lon'); lon=netcdf.getVar(ncid,varid);
varid=netcdf.inqVarID(ncid,'time'); time=netcdf.getVar(ncid,varid);
varid=netcdf.inqVarID(ncid,'lsp'); prec=netcdf.getVar(ncid,varid);
netcdf.close(ncid);

halflat=mean([lat(2:end)';lat(1:end-1)']);
halflon=mean([lon(2:end)';lon(1:end-1)']);
lon(lon>180)=lon(lon>180)-360;
halflon(halflon>180)=halflon(halflon>180)-360;

ilat=find(halflat>=latlim(1) & halflat<=latlim(2));
ilon=find(halflon>=lonlim(1) & halflon<=lonlim(2));

for i=1:length(ilat)
  m_plot(lonlim,repmat(halflat(ilat(i)),1,2),'w-');
end
for i=1:length(ilon)
  m_plot(repmat(halflon(ilon(i)),1,2),latlim,'w-');
end

ilat=find(lat>=latlim(1) & lat<=latlim(2));
ilon=find(lon>=lonlim(1) & lon<=lonlim(2));

prec=prec(ilon,ilat,:,:);

p=reshape(prec,[length(ilon) length(ilat) 12 220]);
ap=sum(p,3);
figure(2);
plot(1:220,squeeze(ap(3,3,:)),'b-');


%%
return



clp_single_redfit('file','data/indus_varves_red.mat','lim',[-50,30],'freqlim',[1/5000 1/5],'xticks',30);
plot_multi_format(1,'../plots/indus_varves_red');

clp_single_redfit('file','data/indus_varves_red.mat','lim',[-50,30],'freqlim',[1/5000 1/30]);
plot_multi_format(1,'../plots/indus_varves_red_centennial');
clp_single_redfit('file','data/indus_varves_red.mat','lim',[-50,30],'freqlim',[1/30 1/5]);
plot_multi_format(1,'../plots/indus_varves_red_decadal');
 
return

%clp_nc_timeseries('file','../../src/test/plasim_11k.nc','latlim',[24,37],'lonlim',[67,76],'variable','lsp');
 

%return
v=clp_varves('timelim',[1901,2010]);
r=clp_cru_bycountry('timelim',[1901,2010]);

figure(5); clf reset;
v.year=flipud(v.year);
v.thick=flipud(v.thick);
plot(v.year,v.thick*100,'r-','Linewidth',4);

hold on;
plot(r.year,r.wetseason,'c-','LineWidth',1);
plot(r.year,movavg(r.year,r.wetseason,3),'b-','LineWidth',2);
legend('Varve thickness','Wet season rain','3-year running');

iyear=1:length(v.year);
[s,p]=corrcoef([v.thick(iyear),r.wetseason(iyear),r.annual(iyear)]);
[i,j]=find(p<0.05);

plot([1964:2010],repmat(60,47,1),'y-','LineWidth',10);
text(1980,60,'Dams','Color','k','FontSize',15);


title('Indus varve thickness and Pakistan rainfall');
plot_multi_format(5,'varves_and_rainfall');

return

% Plot SWAT valley data
variables='pre';
nosum=1;
file='data/cru_ts_3_00.1901.2006.pre.nc';
mult=0.1;
lim=[0 600];
clp_nc_timeseries('nosum',nosum,'mult',mult,'lim',lim,'latlim',[35,35.3],'lonlim',[71.7,71.8],'file',file,'variables',variables,'figoffset',0,'timestep',12,'timelim',[31*12+7,141*12+7]);
title('August precip 35.25N 71.75W from CRU TS3.0');
plot(datenum(now),217,'md','MarkerSize',20,'MarkerFaceColor','m');
plot_multi_format(3,'precipitation_dir');


figure(1);
clf reset;
m_proj('equidistant','lat',[23 38],'lon',[60 78]);
m_coast('patch',[1 .80 .7]);
m_elev('contourf',[250:250:8000]);
m_grid('box','fancy','tickdir','in');
colormap(flipud(bone));
m_gshhs('ib','color','red','linewidth',1.5,'linestyle',':'); % plot boundaries in high resolution
m_gshhs('hr'); % plot boundaries in high resolution
m_plot(71+52/60.+29.72/3600.,35+11/60.+51.58/3600.,'ro','MarkerFaceColor','r','MarkerEdgeColor','k','MarkerSize',10); % Dir, PK
m_text(72.5,35+11/60.+51.58/3600.,'Dir','Color','r','FontSize',14);
m_plot(68+52/60.+1.57/3600,27+41/60.+19.03/3600.,'ro','MarkerFaceColor','r','MarkerEdgeColor','k','MarkerSize',10); % Sukkur, PK
m_text(68,28.3,'Sukkur','Color','r','FontSize',14);

plot_multi_format(1,'map_of_pakistan')


% Plots CRU TS 3.0 timeseries of precipitation in various areas of Pakistan
variables='pre';
nosum=1;
file='data/cru_ts_3_00.1901.2006.pre.nc';
mult=0.1;
lim=[0 1000];
clp_nc_timeseries('nosum',nosum,'mult',mult,'lim',lim,'latlim',[33,37],'lonlim',[70,76],'file',file,'variables',variables,'figoffset',0);
title('Hindukush rainfall from CRU TS3.0');
plot_multi_format(gcf,'precipitation_hindukush');

clp_nc_timeseries('nosum',nosum,'mult',mult,'lim',lim,'latlim',[30,33],'lonlim',[70,77],'file',file,'variables',variables,'figoffset',1);
title('Punjab rainfall from CRU TS3.0');
plot_multi_format(gcf,'precipitation_punjab');

clp_nc_timeseries('nosum',nosum,'mult',mult,'lim',lim,'latlim',[24,30],'lonlim',[67,72],'file',file,'variables',variables,'figoffset',2);
title('Sindh rainfall from CRU TS3.0');
plot_multi_format(gcf,'precipitation_sindh');


clp_ncep_timeseries('latlim',[24,30],'lonlim',[67,72],'lim',[0 200]);
clp_ncep_timeseries('latlim',[30,33],'lonlim',[70,77],'lim',[0 200]);
clp_ncep_timeseries('latlim',[33,37],'lonlim',[70,76],'lim',[0 200]);

end