%% Zimbabwe plots

% also see do_zimbabwe_climate.m

fdir='/Users/lemmen/projects/zimbabwe/netlogo/data';

latlim=[-24 -14];
lonlim=[24 34];

figure(1); clf reset;
m_proj('equidist','lat',latlim,'lon',lonlim);
m_grid;


%% Prepare all naturalearth shape data
ndir='/Users/lemmen/devel/glues/data/naturalearth';

shpnames={
'10m_admin_0_boundary_lines_land.shp',...
'10m_admin_0_countries.shp',...
'10m_admin_0_map_subunits.shp',...
'10m_admin_0_map_units.shp',...
'10m_admin_0_scale_ranks.shp',...
'10m_admin_0_sovereignty.shp',...
'10m_admin_1_states_provinces_lakes_shp.shp',...
'10m_admin_1_states_provinces_lines_shp.shp',...
'10m_admin_1_states_provinces_shp.shp',...
'10m_populated_places.shp',...
'10m_populated_places_simple.shp',...
'10m_railroads.shp',...
'10m_roads.shp',...
'10m_urban_areas.shp',...
'10m_urban_areas_landscan.shp',...
'ne_10m_rivers_lake_centerlines.shp'};

for i=1:length(shpnames)
  cl_shapezoom('file',fullfile(ndir,shpnames{i}),'lat',latlim,'lon',lonlim,'noreplace',1);
end


%lsa=shaperead('/Users/lemmen/projects/zimbabwe/netlogo/data/late stone age.shp');

noprint=1;





