/* Caleb T.
I have updated this file to use some C++ file IO.
*/
#include <iostream>
#include <string>
#include <fstream>
#include <sstream>
#include <cstdlib>

//#define DEBUG 0

int main(int argc, char* argv[]) 
{
  unsigned long int seed=123456789;
  std::string rangeFile;
  std::string valueFile;
  std::string typus;
  std::string name;
  std::ifstream inFile;
  std::ofstream outFile;
  double minval,maxval,val;
  minval = maxval = val = 0.0;

  if (argc > 1)
  {
	  std::stringstream ss;
	  ss << argv[1];
	  ss >> seed;
	  std::cout << "Program " << argv[0] << " called with arguments " << argv[0] << ',' <<
		  argv[1] << "; seed = " << seed << std::endl;
  }
  
  srand(seed);

  rangeFile = "../variation/variation_ranges.tsv";
  valueFile = "../variation/variation_values.tsv";

  inFile.open( rangeFile.c_str(), std::ios::in );
  if( !inFile.is_open() )
	  return 1;

  outFile.open( valueFile.c_str(), std::ios::out );
  if( !outFile.is_open() )
	  return 2;

  outFile << "# File automatically generated by program " << argv[0] << '\n';
  outFile << "# Seed value for this run is " << seed << '\n';

  while( inFile >> typus
	  && inFile >> name
	  && inFile >> minval
	  && inFile >> maxval )
  {
	  val=(1.0*rand())/RAND_MAX*(maxval-minval)+minval;
	  outFile << typus << '\t' << name << '\t' << val << '\n';
  }

  inFile.close();
  outFile.close();

  return 0;
}
