// C++ Code automatically generated by 'XSiSi 2.0'
// Emitted at Thu May 19 22:53:41 CEST 2005

// Please read the documentation!

// Please note: This file will not be overwritten in future times.

#ifndef _MySiSi_hh_
#define _MySiSi_hh_
// Here you can insert class and/or struct definitions
// needed by SiSi's parser.
// (You can also place #include's here!)
#endif // _MySiSi_hh_
